### ISSUE TITLE
[9.0] Is this module compatible with 9.0?

### ISSUE THREAD

**Issue by lukebranch** [techhighway/Product-Wishlist#1]
Thanks for building this module. Is this compatible with 9.0? I'm getting some tracebacks with view errors when trying to install in 9.0 CE.

```
Error context:
View `Header`
[view_id: 1123, xml_id: n/a, model: n/a, parent_id: 745]
None" while parsing None:34, near
<data inherit_id="website_sale.cart" name="Header">
    <xpath expr="//span[@t-field='line.product_id.image_small']" position="after">
        <t t-set="int_prod_qty" t-value="website.is_product_in_wishlist(line.product_id.id)"/> 
        <input type="hidden" name="product_id" t-att-value="line.product_id.id"/>
        <a onclick="add_product_to_wishlist_from_cart(this)" class="fa fa-shopping-wishlist_new" t-if="not int_prod_qty"/>
        <a id="add_product_to_wishlist_from_cart" t-attf-href="#" onclick="add_product_to_wishlist_from_cart(this)" href="#" t-if="not int_prod_qty">Add to wishlist</a>
     </xpath>
</data>
```

**Comment by techhighway** [comment]
Hello,
Thank you for your email.
We have resolved this issue. Please download it once again and install it.

**Comment by lukebranch** [comment]
@techhighway ,

Thanks for the fix. I have just noticed another issue. Unfortunately features like /shop/view_my_wishlist do not seem to be available to public (ie. not logged in) users which results in a 403 forbidden error when trying to access that page among others.

I think this is because Odoo defaults to admin-only user rights if access rights are not specifically defined.
